### ISSUE TITLE
Build broken on OS X?

### ISSUE THREAD

**Issue by sevan** [9fans/plan9port#66]
Just pulled the latest sources & attempted to rebuild.
Process failed.

`>>> cd /usr/local/plan9/src/cmd/devdraw; mk all           
9c -DOSX_VERSION=101106 -o cocoa-screen-objc.o cocoa-screen.m
cocoa-screen.m:376:13: error: use of undeclared identifier 'NSWindowStyleMaskTitled'
cocoa-screen.m:377:5: error: use of undeclared identifier 'NSWindowStyleMaskClosable'
cocoa-screen.m:378:5: error: use of undeclared identifier 'NSWindowStyleMaskMiniaturizable'
cocoa-screen.m:379:5: error: use of undeclared identifier 'NSWindowStyleMaskResizable'
cocoa-screen.m:428:13: error: use of undeclared identifier 'NSWindowStyleMaskBorderless'
cocoa-screen.m:600:14: error: use of undeclared identifier 'NSCompositingOperationCopy'
cocoa-screen.m:605:14: error: use of undeclared identifier 'NSCompositingOperationSourceIn'
cocoa-screen.m:609:14: error: use of undeclared identifier 'NSCompositingOperationSourceIn'
cocoa-screen.m:614:14: error: use of undeclared identifier 'NSCompositingOperationCopy'
cocoa-screen.m:688:12: error: use of undeclared identifier 'NSCompositingOperationSourceIn'
cocoa-screen.m:899:7: error: use of undeclared identifier 'NSEventTypeKeyDown'; did you mean 'NSEventTypeGesture'?
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:47:5: note: 'NSEventTypeGesture' declared here
cocoa-screen.m:905:10: error: use of undeclared identifier 'NSEventModifierFlagCommand'
cocoa-screen.m:922:7: error: use of undeclared identifier 'NSEventTypeFlagsChanged'; did you mean 'kCGEventFlagsChanged'?
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEventTypes.h:117:3: note: 'kCGEventFlagsChanged' declared here
cocoa-screen.m:925:11: error: use of undeclared identifier 'NSEventModifierFlagOption'
cocoa-screen.m:927:11: error: use of undeclared identifier 'NSEventModifierFlagCommand'
cocoa-screen.m:931:8: error: use of undeclared identifier 'NSEventModifierFlagOption'
cocoa-screen.m:931:36: error: use of undeclared identifier 'NSEventModifierFlagOption'
cocoa-screen.m:979:12: error: use of undeclared identifier 'NSWindowStyleMaskResizable'
cocoa-screen.m:985:23: error: use of undeclared identifier 'NSWindowStyleMaskResizable'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
mk: 9c -DOSX_VERSION=101106 -o ...  : exit status=exit(1)
mk: for i in ...  : exit status=exit(1)
mk: for i in ...  : exit status=exit(1)`

**Comment by marciol** [comment]
+1

**Comment by marciol** [comment]
@sevan  seems that you like me, are using a old version of Mac Os X, so the build failed.

The problem is related to this commit from @rsc 

https://github.com/9fans/plan9port/commit/310ae03327a815e721166b64aa3af27b1cc8c2ff

I commented out this excerpt of code and it worked out, as follow:

https://github.com/9fans/plan9port/blob/master/src/cmd/devdraw/cocoa-screen.m#L32:L53

**Comment by glycerine** [comment]
I also couldn't build on osx 10.11.6. Filed https://github.com/9fans/plan9port/issues/74 to fix this.

**Comment by 0intro** [comment]
This issue was fixed in commit ff5bedadc0be4511a3c1d61a3e91516915c9d518.

**Comment by 0intro** [comment]
Thanks for noticing. The change is now merged in commit 680c57a15c51c302d89aec134e25f08820d3f30d.

**Comment by jamie-digital** [comment]
I just got exactly the same behaviour on High Sierra (10.13.1, DOSX_VERSION=101301). Changing the `#ifdef` introduced in 680c57a to `#ifdef 0` fixed the problem. Perhaps the `#ifdef` needs another clause ignoring 101301+?
