### ISSUE TITLE
fontsrv fails to build on OS X Tiger due to lack of Core Text

### ISSUE THREAD

**Issue by sevan** [9fans/plan9port#161]
Core Text was introduced in Leopard (10.5)
Attempting to build on Tiger (10.4) fails with

> >>> cd /usr/local/plan9/src/cmd/fontsrv; mk all   
> 9c  osx.c
> osx.c:82: error: 'CTFontCollectionRef' undeclared
> osx.c:82: error: parse error before 'allc'
> osx.c:85: error: 'CTFontDescriptorRef' undeclared
> osx.c:85: error: parse error before 'f'
> osx.c:87: error: 'allc' undeclared
> osx.c:87: warning: implicit declaration of function 'CTFontCollectionCreateFromAvailableFonts'
> osx.c:88: warning: implicit declaration of function 'CTFontCollectionCreateMatchingFontDescriptors'
> osx.c:88: warning: assignment makes pointer from integer without a cast
> osx.c:92: error: 'f' undeclared
> osx.c:95: warning: implicit declaration of function 'CTFontDescriptorCopyAttribute'
> osx.c:95: error: 'kCTFontNameAttribute' undeclared
> osx.c:95: warning: assignment makes pointer from integer without a cast
> osx.c:120: error: 'CTFontRef' undeclared
> osx.c:120: error: parse error before 'font'
> osx.c:121: error: 'CTFontDescriptorRef' undeclared
> osx.c:126: error: 'desc' undeclared
> osx.c:126: warning: implicit declaration of function 'CTFontDescriptorCreateWithNameAndSize'
> osx.c:130: warning: implicit declaration of function 'CTFontCreateWithFontDescriptor'
> osx.c:130: warning: assignment makes pointer from integer without a cast
> osx.c:141: error: 'kCTFontAttributeName' undeclared
> osx.c:147: error: 'CTLineRef' undeclared
> osx.c:147: error: parse error before 'line'
> osx.c:160: warning: implicit declaration of function 'CTLineCreateWithAttributedString'
> osx.c:160: error: invalid lvalue in assignment
> osx.c:160: warning: statement with no effect
> osx.c:161: warning: implicit declaration of function 'CTLineGetImageBounds'
> osx.c:161: error: incompatible types in assignment
> osx.c:161: warning: statement with no effect
> osx.c:215: error: 'CTFontRef' undeclared
> osx.c:215: error: parse error before 'font'
> osx.c:216: error: 'CTFontDescriptorRef' undeclared
> osx.c:223: error: 'CGFloat' undeclared
> osx.c:223: error: parse error before 'whitef'
> osx.c:227: error: 'desc' undeclared
> osx.c:227: warning: statement with no effect
> osx.c:231: warning: assignment makes pointer from integer without a cast
> osx.c:237: warning: implicit declaration of function 'CTFontGetBoundingBox'
> osx.c:237: error: incompatible types in assignment
> osx.c:237: warning: statement with no effect
> osx.c:268: error: 'whitef' undeclared
> osx.c:268: warning: passing argument 2 of 'CGColorCreate' from incompatible pointer type
> osx.c:287: error: 'CTLineRef' undeclared
> osx.c:287: error: parse error before 'line'
> osx.c:290: error: 'kCTFontAttributeName' undeclared
> osx.c:290: error: 'kCTForegroundColorAttributeName' undeclared
> osx.c:305: error: invalid lvalue in assignment
> osx.c:305: warning: statement with no effect
> osx.c:307: error: incompatible types in assignment
> osx.c:307: warning: statement with no effect
> osx.c:309: warning: implicit declaration of function 'CTLineDraw'
> mk: 9c  osx.c  : exit status=exit(1)
