### ISSUE TITLE
‘struct dirent’ has no member named ‘d_namlen’

### ISSUE THREAD

**Issue by neeshy** [9fans/plan9port#395]
According to https://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html d_namlen
is BSD extension which isn't specified by POSIX. Using d_namlen causes build failures on Linux.

```
9c open.c
open.c:321:21: error: 'struct dirent' has no member named 'd_namlen'; did you mean 'd_name'?
  321 |   if(de->d_name[de->d_namlen] != 0)
      |                     ^~~~~~~~
      |                     d_name
```

Regression introduced by https://github.com/9fans/plan9port/commit/8cb7308f3a24249ed091c7decf22005c64099783

**Comment by gdiazlo** [comment]
On my system, d_namlen is not present, seems that in dirent.h there are macros for compatibility with systems that have either d_namlen or d_reclen.

Changing it to:

if(de->d_name[_D_EXACT_NAMLEN(de)] != 0

everything builds, but I have core dumps when executing sam or acme as stated in #396 

That basically substitutes d_namlen by strlen(d_name) on systems with no d_namlen.

But that's with the dirent.h I have which appears to come from glibc 2.3.
